version: '3.8'
services:
  app:
    build: .
    container_name: api_e_contrib
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=anderson
      - DB_PASS=126303@acv
      - DB_NAME=db_gestaotributaria_riachaodojacuipe
      - DB_PORT=3306
    depends_on:
      - db
  db:
    image: mysql:8
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 126303@acv
      MYSQL_DATABASE: db_gestaotributaria_riachaodojacuipe
    ports:
      - "3306:3306"
