# Configurações de build
[build]
  command = "npm install"  # Instala dependências
  publish = "public"       # Pasta de publicação (pode ser ignorado para API)
  functions = "netlify/functions"  # Diretório onde estão as funções da API

# Definindo redirecionamento para chamadas de API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
