[build]
  # Comando de build (caso tenha algum processo de build, como compilação ou minificação)
  command = "npm run build"
  
  # Diretório de publicação. Aqui não é necessário especificar o 'public' se for apenas a API.
  publish = "/opt/build/repo"  # O diretório raiz onde a aplicação e funções estão.

[functions]
  # Definindo que todas as funções na pasta netlify/functions usarão o esbuild.
  '*'
    node_bundler = "esbuild"

[functionsDirectory]
  # Diretório onde estão as funções (no seu caso, será a pasta netlify/functions)
  directory = "netlify/functions"

[redirects]
  # Redirecionando as rotas da API para as funções serverless
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
