# Definindo as configurações de build e funções do Netlify
[build]
  command = "npm install"
  
  # Remove o publish porque é uma API, não um site estático
  # publish = "public"

# Definindo a pasta de funções para o Netlify
[functions]
  directory = "netlify/functions"

# Definindo redirecionamentos para usar funções API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
