[build]
  command = "npm run build"  
  functions = "netlify/functions" 
  publish = "/"  

[functions]
  directory = "netlify/functions" 
  node_bundler = "esbuild"  
  
[[redirects]]
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/:splat"  

[[plugins]]
  package = "@netlify/plugin-functions-installation"  
