[build]
  command = "npm install"  # Comando para instalar dependências
  publish = "public"       # Caso você não tenha uma pasta 'public', pode deixar assim ou removê-la
  functions = "netlify/functions"  # Pasta onde suas funções serverless estão

[[plugins]]
  package = "@netlify/plugin-functions-installation"   # Plugin para instalar as dependências das funções serverless

[redirects]
  from = "/api/*"  # Redireciona todas as requisições para a função
  to = "/.netlify/functions/:splat"  # Especifica que a rota será tratada pelas funções
  status = 200
