[build]
  command = "npm run build"
  publish = "/opt/build/repo"  

[functions]
  node_bundler = "esbuild"

[functionsDirectory]
  directory = "netlify/functions"

[redirects]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
