openapi: 3.0.0
info:
  title: API de Contribuintes
  description: API para consultar dados de contribuintes
  version: 1.0.0

servers:
  - url: http://localhost:8888/api
    description: Servidor local

paths:
  /contribuintes:
    get:
      summary: Consulta dados dos contribuintes
      description: Retorna uma lista de todos os contribuintes com informações detalhadas e valores de DAM.
      operationId: getContribuintes
      tags:
        - Contribuintes
      responses:
        '200':
          description: Consulta realizada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Consulta realizada com sucesso."
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        nome:
                          type: string
                          example: "Empresa XYZ"
                        dados:
                          type: object
                          properties:
                            tipo:
                              type: string
                              example: "Jurídica"
                            cpf_cnpj:
                              type: string
                              example: "12345678000195"
                            fantasia:
                              type: string
                              example: "Empresa XYZ"
                            email:
                              type: string
                              example: "contato@empresa.com"
                            telefone:
                              type: string
                              example: "123456789"
                            celular:
                              type: string
                              example: "987654321"
                        endereco:
                          type: object
                          properties:
                            pais:
                              type: string
                              example: "Brasil"
                            cidade_estado:
                              type: string
                              example: "São Paulo/SP"
                            tipo_logradouro:
                              type: string
                              example: "Avenida"
                            bairro:
                              type: string
                              example: "Centro"
                            cep:
                              type: string
                              example: "40000000"
                            endereco:
                              type: string
                              example: "Av. Paulista"
                            numero:
                              type: string
                              example: "100"
                            complemento:
                              type: string
                              example: "Sala 101"
                            site:
                              type: string
                              example: "www.empresa.com.br"
                        dam:
                          type: array
                          items:
                            type: object
                            properties:
                              sigla:
                                type: string
                                example: "DAM1"
                              valor_total:
                                type: number
                                format: float
                                example: 5000.50
        '500':
          description: Erro ao buscar dados
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Erro ao buscar dados"
