version: "3.8"
services:
  app:
    build: .
    container_name: api-gestao
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=anderson
      - DB_PASS=126303@acv
      - DB_NAME=db_gestaotributaria_riachaodojacuipe
      - DB_PORT=3306
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: mysql-gestao
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_gestaotributaria_riachaodojacuipe
      MYSQL_USER: anderson
      MYSQL_PASSWORD: 126303@acv
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
